### ISSUE TITLE
Return callback not working

### ISSUE THREAD

**Issue by jasenkoh** [blitline-dev/simple_blitline_node#14]
Response for following example is always empty (never reached)

```blitline.postJobs( function(response) {
    console.log(response);
})```

Although if I console log in following code, I see that request was executed successfully:

```
res
  .on('data', function(chunk) {
    return result.push(chunk.toString());
  })
  .on('end', function() {
    console.log(result.join(''));
    // when the response ends, send the response back to the callback
    return resolve(JSON.parse(result.join('')));
  });```

**Comment by blitline-dev** [comment]
blitline.postJobs returns a promise. The promise should then be listened to...so for example:

    var promise = blitline.postJobs();
      promise.then(function(data) {
        console.log(data);
    });

**Comment by jasenkoh** [comment]
Yeah, I figured it out too just now too when I realized it's a promise response
